services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    Sylius\Component\Channel\Context\ChannelContextInterface: '@sylius.context.channel.cached'
    MangoSylius\PaymentFeePlugin\Form\Type\Calculator\FlatRateConfigurationType: ~
    MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculatorInterface: '@MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator'

    MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator:
        arguments:
            $registry: '@mango_sylius.payment_fee_plugin.registry.payment_calculator'

    MangoSylius\PaymentFeePlugin\Form\Type\CalculatorChoiceType:
        arguments:
            $calculators: '%mango_sylius.payment_fee_plugin.payment_fee_calculators%'
        tags:
            - name: form.type

    MangoSylius\PaymentFeePlugin\Form\Extension\PaymentMethodTypeExtension:
        arguments:
            $calculatorRegistry: '@mango_sylius.payment_fee_plugin.registry.payment_calculator'
            $formTypeRegistry: '@mango_sylius.payment_fee_plugin.form_registry.payment_calculator'
        tags:
            - extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType
              name: form.type_extension

    MangoSylius\PaymentFeePlugin\Form\Extension\PaymentMethodChoiceTypeExtension:
        arguments:
            $calculatorRegistry: '@mango_sylius.payment_fee_plugin.registry.payment_calculator'
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodChoiceType

    mango_sylius.payment_fee_plugin.registry.payment_calculator:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            $context: payment fee calculator
            $className: MangoSylius\PaymentFeePlugin\Model\Calculator\CalculatorInterface

    mango_sylius.payment_fee_plugin.form_registry.payment_calculator:
        class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    MangoSylius\PaymentFeePlugin\Model\Calculator\FlatRateCalculator:
        tags:
            - calculator: flat_rate
              form_type: MangoSylius\PaymentFeePlugin\Form\Type\Calculator\ChannelBasedFlatRateConfigurationType
              label: 'mango-sylius.form.payment_calculator.flat_rate_configuration.label'
              name: MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator

    MangoSylius\PaymentFeePlugin\Model\PaymentChargesProcessor:
        arguments:
            $adjustmentFactory: '@sylius.factory.adjustment'
            $paymentChargesCalculator: '@MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator'
        tags:
            - name: sylius.order_processor
              priotiry: 0

    mango_sylius.payment_fee_plugin.order_processing.order_payment_processor.checkout:
        class: Sylius\Component\Core\OrderProcessing\OrderPaymentProcessor
        arguments:
            - '@sylius.order_payment_provider'
        tags:
            - name: sylius.order_processor
              priotiry: 5

    mango_sylius.payment_fee_plugin.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@MangoSyliusPaymentFeePlugin/Admin/_javascripts.html.twig'
        tags:
            - event: sonata.block.event.sylius.admin.layout.javascripts
              method: onBlockEvent
              name: kernel.event_listener

    MangoSylius\PaymentFeePlugin\Model\Taxation\Applicator\OrderPaymentTaxesApplicator:
        arguments:
            $calculator: '@sylius.tax_calculator'
            $adjustmentFactory: '@sylius.factory.adjustment'
            $taxRateResolver: '@sylius.tax_rate_resolver'
